language: ruby
rvm:
  - 2.3.1

before_install:
  - sudo apt-get install -y cmake libssh2-1-dev

install:
  - travis_wait bundle install --path=~/.bundle --jobs=3 --retry=3 --without development production console
  - sudo apt-get install -y libaprutil1-dev swig
  - wget http://apache.parentingamerica.com/subversion/subversion-1.9.5.tar.gz
  - tar xzf subversion-1.9.5.tar.gz
  - wget https://www.sqlite.org/sqlite-amalgamation-3071501.zip
  - unzip sqlite-amalgamation-3071501.zip
  - mv sqlite-amalgamation-3071501 subversion-1.9.5/sqlite-amalgamation
  - cd subversion-1.9.5
  - LDFLAGS="-L/home/travis/.rvm/rubies/ruby-2.3.1/lib/" ./configure --prefix=/home/travis/.rvm/rubies/ruby-2.3.1/
  - make
  - make swig-rb
  - make install
  - make install-swig-rb
  - cd ..

before_script:
  - sudo rm -f /etc/localtime
  - sudo ln -s /usr/share/zoneinfo/US/Eastern /etc/localtime
  - cp config/database.yml.ci config/database.yml
  - psql -c 'create database markus_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  - bundle exec rake test
  - bundle exec rspec

notifications:
  email: false

bundler_args: --retry 10

cache:
  directories:
  - ~/.bundle
