language: ruby
rvm:
  - 2.1.2

before_install:
  - sudo echo host localhost >> ~/.ssh/config
  - sudo echo   user git >> ~/.ssh/config
  - sudo echo   identityfile ~/git >> ~/.ssh/config
  - sudo echo   port 22 >> ~/.ssh/config
  - sudo echo NoHostAuthenticationForLocalhost yes >> ~/.ssh/config
  - sudo apt-get update -qq
  - sudo apt-get install -y sshpass
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  - sudo adduser -disabled-password --gecos "" git
  - echo "git:password" | sudo chpasswd
  - sudo adduser git sudo
  - sudo cp ~/.ssh/id_rsa.pub /home/git/git.pub
  - sudo cp ~/.ssh/id_rsa /home/git/git
  - sudo chmod 777 /home/git/git.pub
  - sudo chmod 777 /home/git/git
  - sudo -H -u git bash -c 'git clone git://github.com/sitaramc/gitolite /home/git/gitolite'
  - sudo -H -u git bash -c 'mkdir /home/git/bin'
  - sudo -H -u git bash -c '/home/git/gitolite/install -ln'
  - sudo -H -u git bash -c 'export PATH="~/bin:$PATH"'
  - sudo -H -u git bash -c '/home/git/bin/gitolite setup -pk /home/git/git.pub'
  - eval $(ssh-agent -s)
  - ssh-add ~/git
  - ssh git@localhost
  - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no git@localhost
  - sudo apt-get install -y cmake libssh2* libgit2* ruby1.9.1-dev
  - git config --global user.email "travis@travis.com"
  - git config --global user.name "Travis CI"

install:
  - bundle install --path=~/.bundle --without development production console
  - sudo apt-get install -y libaprutil1-dev swig
  - wget http://mirror.its.dal.ca/apache/subversion/subversion-1.8.11.tar.gz
  - tar xzf subversion-1.8.11.tar.gz
  - wget http://www.sqlite.org/sqlite-amalgamation-3071501.zip
  - unzip sqlite-amalgamation-3071501.zip
  - mv sqlite-amalgamation-3071501 subversion-1.8.11/sqlite-amalgamation
  - cd subversion-1.8.11
  - LDFLAGS="-L/home/travis/.rvm/rubies/ruby-2.1.2/lib/" ./configure --prefix=/home/travis/.rvm/rubies/ruby-2.1.2/
  - make
  - make swig-rb
  - make install
  - make install-swig-rb
  - cd ..

before_script:
  - sudo rm -f /etc/localtime
  - sudo ln -s /usr/share/zoneinfo/US/Eastern /etc/localtime
  - cp config/database.yml.ci config/database.yml
  - psql -c 'create database markus_test;' -U postgres
  - bundle exec rake db:migrate
  - bundle exec rake db:test:prepare

script:
  - bundle exec rake test
  - bundle exec rspec

notifications:
  email: false
