language: ruby
rvm:
  - 2.5.3
dist: bionic
addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10

before_install:
  - sudo apt-get update
  - sudo apt-get install -y cmake libssh2-1-dev ghostscript
  - sudo apt-get install imagemagick libmagickwand-dev

install:
  - travis_wait bundle install --path=~/.bundle --jobs=3 --retry=3 --without development production console
  - yarn install
  #  - ./script/install-svn.sh  # uncomment this if we want to test interactions with svn in the future
  - cp config/database.yml.ci config/database.yml

before_script:
  - sudo rm -f /etc/localtime
  - sudo ln -s /usr/share/zoneinfo/US/Eastern /etc/localtime
  - bundle exec rake i18n:js:export
  - chmod u+x bin/webpack
  - RAILS_ENV=test bundle exec rake webpacker:compile
  - psql -c 'create database markus_test;' -U postgres
  - bundle exec rake db:migrate RAILS_ENV=test

script:
  # - bundle exec rake test # shoulda (with rails 5) compatibility issues
  - bundle exec rspec

services:
  - postgresql
  - redis-server

notifications:
  email: false

bundler_args: --retry 10

cache:
  yarn: true
  directories:
    - ~/.bundle
    - node_modules
