rails:
  cache_classes: true
  eager_load: true
  consider_all_requests_local: false
  log_level: info
  force_ssl: true
  active_support:
    deprecation: silence
  action_controller:
    perform_caching: true
  session_store:
    args:
      secret: 650d281667d8011a3a6ad6dd4b5d4f9ddbce14a7d78b107812dbb40b24e234256ab2c5572c8196cf6cde6b85942688b6bfd337ffa0daee648d04e1674cf1fdf6
      secure: true
  action_mailer:
    delivery_method: smtp
    smtp_settings: {}
    perform_deliveries: false

i18n:
  available_locales:
    - en
  default_locale: en

validate_user_not_allowed_message: ~
incorrect_login_message: ~

logging:
  log_file: log/info_production.log
  error_file: log/error_production.log

autotest:
  max_batch_size: 500

# The settings below are for an experimental feature that is not available
# in production yet. Please disregard for now.
lti:
  domains: <%= %w[canvas.instructure.com] %>
  token_endpoint: "https://canvas.instructure.com/login/oauth2/token"
