rails:
  cache_classes: true
  eager_load: false
  consider_all_requests_local: true
  log_level: debug
  active_job:
    queue_adapter: test
  active_support:
    deprecation: stderr
  action_mailer:
    perform_deliveries: true

i18n:
  available_locales:
    - en
  default_locale: en

validate_user_not_allowed_message: ~
incorrect_login_message: ~

validate_file: <%= "#{::Rails.root}/config/dummy_validate.sh" %>
remote_auth_login_url: https://www.example.com

repository:
  type: mem

logging:
  log_file: log/info_test.log
  error_file: log/error_test.log

autotest:
  max_batch_size: 10

# The settings below are for an experimental feature that is not available
# in production yet. Please disregard for now.
lti:
  domains: <%= %w[test.host] %>
  token_endpoint: "http://test.host.com/login/oauth2/token"
