rails:
  cache_classes: true
  eager_load: false
  consider_all_requests_local: true
  log_level: debug
  active_support:
    deprecation: stderr
  action_mailer:
    perform_deliveries: true

i18n:
  available_locales:
    - en
    - fr
    - es
    - pt
  default_locale: en

validate_user_not_allowed_message: ~
incorrect_login_message: ~

repository:
  type: mem
  storage: <%= "#{::Rails.root.to_s}/data/test" %>/repos
  
logging:
  log_file: log/info_test.log
  error_file: log/error_test.log

autotest:
  client_dir: <%= "#{::Rails.root.to_s}/data/test" %>/autotest
  max_batch_size: 10

scanned_exams:
  path: <%= "#{::Rails.root.to_s}/data/test" %>/exam_templates

starter_file:
  storage: <%= "#{::Rails.root.to_s}/data/test" %>/starter_files
